name: api-star-fitness CI
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repositório
              uses: actions/checkout@v1
            - name: Deploy Hostinger
              uses: easingthemes/ssh-deploy@main
              env:
                SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
                ARGS: "-rltgoDzvO --delete"
                SOURCE: "/"
                REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
                REMOTE_USER: ${{ secrets.REMOTE_USER }}
                REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
                TARGET: ${{ secrets.REMOTE_TARGET }}